#!/usr/bin/env python3
"""Build a ground-truth manifest for one folio page.

Downloads the Cantus CSV for a manuscript source, splits each chant's text
into per-line fragments using volpiano 7 markers, and writes a JSON manifest
mapping HTRflow node labels to their Cantus text fragments.

Usage
-----
python scripts/build_gt_manifest.py \\
    --source-id 123723 \\
    --folio "006r" \\
    --node-labels-file node_labels.txt \\
    --output data/manifests/manifest_006r.json

The node-labels file should contain one HTRflow node label per line, e.g.::

    CH-Fco_Ms._2_006r_copy_region0_line0
    CH-Fco_Ms._2_006r_copy_region0_line1
    ...

Node labels are generated by HTRflow's relabelling step and can be read from
the id attributes of <TextLine> elements in PAGE XML output.

The Cantus source ID for a manuscript is listed on cantusdatabase.org on the
source's detail page.  A data/cantus_sources.yaml config file can be used to
record sigla → source_id mappings for manuscripts used in this project.
"""

import argparse
import json
import logging
import sys
from pathlib import Path

# Make the repo root importable when running as a script
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from steps.gt_manifest import build_page_manifest, fetch_cantus_csv

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Build a gt_lookup manifest from the Cantus CSV.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--source-id",
        type=int,
        required=True,
        metavar="INT",
        help="Cantus source ID (integer, from cantusdatabase.org).",
    )
    parser.add_argument(
        "--folio",
        required=True,
        metavar="STR",
        help='Folio string exactly as it appears in the Cantus CSV, e.g. "006r".',
    )
    parser.add_argument(
        "--node-labels-file",
        required=True,
        metavar="PATH",
        help="Text file with one HTRflow node label per line, in reading order.",
    )
    parser.add_argument(
        "--output",
        required=True,
        metavar="PATH",
        help="Destination JSON file for the manifest.",
    )
    args = parser.parse_args()

    node_labels_path = Path(args.node_labels_file)
    if not node_labels_path.exists():
        parser.error(f"Node labels file not found: {node_labels_path}")

    node_labels = [
        line.strip()
        for line in node_labels_path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    if not node_labels:
        parser.error(f"No node labels found in {node_labels_path}")

    logger.info("Loaded %d node labels from %s", len(node_labels), node_labels_path)

    csv_rows = fetch_cantus_csv(args.source_id)
    logger.info("Fetched %d CSV rows for source %d", len(csv_rows), args.source_id)

    manifest = build_page_manifest(csv_rows, args.folio, node_labels)
    logger.info(
        "Built manifest: %d / %d node labels matched",
        len(manifest),
        len(node_labels),
    )

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2, ensure_ascii=False)

    logger.info("Wrote manifest to %s", out_path)


if __name__ == "__main__":
    main()
